### ISSUE TITLE
The "NXdata.plot" method does not work with linked signal 

### ISSUE THREAD

**Issue by BalazsBago** [nexpy/nexusformat#136]
Using the plot method of the NXdata class throws an attribute error, if the signal is an NXlinkfield.
Example:

```python
import numpy
from nexusformat import nexus


def main():
    data = numpy.random.rand(50, 100)
    axis_x = numpy.array(range(50))
    axis_y = numpy.array(range(100))

    nx = nexus.NXroot()
    nx.entry = nexus.NXentry()
    nx.entry.instrument = nexus.NXinstrument()
    nx.entry.instrument.detector = nexus.NXdetector()

    nx.entry.instrument.detector.data = nexus.NXfield(value=data)

    # Data
    nx.entry.data = nexus.NXdata(
        signal=nexus.NXlinkfield(target='/entry/instrument/detector/data'),
        axes=(
            nexus.NXfield(value=axis_x, name='X'),
            nexus.NXfield(value=axis_y, name='Y'),
        )
    )
    nx.entry.data.set_default(True)
    print(nx.tree)
    nx.entry.data.plot()

if __name__ == '__main__':
    main()
```

OS: Ubuntu 18.04
Python: 3.6
nexusformat: 0.6.0

**Comment by rayosborn** [comment]
Thanks for raising the issue. I was aware of a related problem when plotting unsaved NeXus data within NeXpy, where it is slightly tricky to fix. However, I hadn't realized that it affects the nexusformat package as well. That is because I mostly work with NeXus trees that are saved to a file; if you save the NXroot group to a file, this problem goes away. However, it's an easy fix to make it work for NXlinkfields that are not saved to a file. I will have to check for any possible side effects, but I might be able to release a fix soon.

**Comment by BalazsBago** [comment]
> Thanks for raising the issue. I was aware of a related problem when plotting unsaved NeXus data within NeXpy, where it is slightly tricky to fix. However, I hadn't realized that it affects the nexusformat package as well. That is because I mostly work with NeXus trees that are saved to a file; if you save the NXroot group to a file, this problem goes away. However, it's an easy fix to make it work for NXlinkfields that are not saved to a file. I will have to check for any possible side effects, but I might be able to release a fix soon.

Thanks for the fast replay. The suggested workaround solves the issues.

**Comment by rayosborn** [comment]
The posted code now works, i.e., without needing to save the NeXus tree to a file, in [v0.6.1](releases/tag/v0.6.1). It is available through pip and conda-forge.
